from .human import CLEANER_HUMAN_PROMPT, FLASHCARDER_HUMAN_PROMPT
from .system import CLEANER_SYSTEM_PROMPT, FLASHCARDER_SYSTEM_PROMPT

__all__ = [
    "CLEANER_SYSTEM_PROMPT",
    "CLEANER_HUMAN_PROMPT",
    "FLASHCARDER_SYSTEM_PROMPT",
    "FLASHCARDER_HUMAN_PROMPT",
]
